# Position Controllers ---------------------------------------
 joint1_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint1
   pid: {p: 5000.0, i: 0.0, d: 10.0}
 joint2_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint2
   pid: {p: 500.0, i: 0.0, d: 500.0}
 joint3_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint3
   pid: {p: 2000.0, i: 0.0, d: 500.0}
 joint4_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint4
   pid: {p: 3000.0, i: 0.0, d: 300.0}
 joint5_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint5
   pid: {p: 300.0, i: 0.0, d: 100.0}
 joint6_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint6
   pid: {p: 5.0, i: 0.0, d: 10.0}